# Requirements for Packages when setting up Conda Environment
name: ds-oncorps-charts
dependencies:
  - requests=2.*
  - pytest=4.1.*
  - Flask=1.0.*
  - pandas=0.25.1
  - numpy=1.*
  - pytest-cov=2.6.*
  - pymongo[srv]
  - dnspython
  - pip
  - pip:
    - more-itertools==4.1.*
    - plotly==3.9.0
    - flask-cors==3.0.*
    - pytz==2019.1
    - arctic
